### ISSUE TITLE
[Pipe] MaybeAsyncPipe

### ISSUE THREAD

**Issue by erzaehlsalex** [Rocketloop/ng-rocketparts#3]
We need to extract our [MaybeAsyncPipe](https://github.com/Rocketloop/ng-rocketparts/files/2344938/maybe-async.pipe.txt) and expose it as part of this library. We also need to create tests for the pipe, before it can be included in the library.

**Comment by flore2003** [comment]
How do we want to handle this pipe in relation to the discussion in #2? I think a separate NgModule for just a single pipe is overkill. Can someone quickly check, if ng-bootstrap exposes pipes, and if yes, how they do it?

**Comment by ditoglez** [comment]
Haven't found in `ng-bootstrap` any pipes export but maybe I just missed it.
Yeah, I agree that making a module for just one pipe is overkill. What about if for now, we just expose it as a standalone pipe and let the user decide to declare it in their own `NgModule` or the component she/he wants?

From the other side, we decided to make an `NgModule` for the `number-input-component`... 🤔
